//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTickets.Infrastructure.Data.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieTickets.Infrastructure.Data.Scripts.DataScripts", typeof(DataScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOCOUNT ON
        ///
        ///SET IDENTITY_INSERT [dbo].[Movie] ON
        ///
        ///DECLARE @mergeOutput TABLE ( [DMLAction] VARCHAR(6) );
        ///MERGE INTO [dbo].[Movie] WITH (SERIALIZABLE) AS [Target]
        ///USING (VALUES
        ///  (11,&apos;Custom Test Movie 1&apos;)
        ///) AS [Source] ([Id],[Name])
        ///ON ([Target].[Id] = [Source].[Id])
        ///WHEN MATCHED AND EXISTS (SELECT [Source].[Name]
        ///                 EXCEPT  SELECT [Target].[Name]) THEN
        /// UPDATE SET
        ///  [Target].[Name] = [Source].[Name]
        ///WHEN NOT MATCHED BY TARGET THEN
        /// INSERT([Id],[Name])
        /// VALUES([Source].[Id] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedCustomMovies {
            get {
                return ResourceManager.GetString("SeedCustomMovies", resourceCulture);
            }
        }
    }
}
